# arguments for dataset
dataset: abdomen_ct
root: /data/qmy/Dataset/Abdomen
n_domains: 6
n_channels: 1
n_classes: 10
n_filters: 32
patch_size: [96, 96, 96]
class_names:
  [
    "background",
    "spleen",
    "kidney.R",
    "kidney.L",
    "gallbladder",
    "esophagus",
    "liver",
    "stomach",
    "pancreas",
    "duodenum",
  ]
# arguments for accelerator
gradient_accumulation_steps: 1 # 1 for no gradient accumulation
mixed_precision: "no" # "no" or "fp16"
balanced: True

# arguments for training
epochs: 200
iters: 250
batch_size: 2
optimizer: adam
lr: 0.1
weight_decay: 0
lr_scheduler: plateau
lr_kwargs:
  mode: "min"
  factor: 0.8   # reduce by 20%
  patience: 10
  threshold: 1.0e-3
  verbose: True

lambda_dice: 4.0
conf_thresh: 0.9

num_workers: 4

# logging / evaluation
logs_each_epoch: 4
warmup_epochs: 0 # skip evaluation for the first N epochs

stride_xy: 16
stride_z: 16
